[package]
name = "lamlock"
version = "0.1.0"
edition = "2024"

[features]
nightly = []

[dependencies]
rustix = { version = "1.0.7", default-features = false, features = ["thread"] }

[[bench]]
name = "lamlock-bench"
harness = false

[dev-dependencies]
criterion = "0.6.0"
