[package]
name = "vdso-rng"
version = "0.1.0"
edition = "2024"

[dependencies]
linux-raw-sys = { version = "0.10.0", default-features = false, features = ["core", "elf", "elf_uapi", "general", "no_std", "prctl"] }
rustix-futex-sync = "0.4.0"
syscalls = { version = "0.6.18", default-features = false }

